apps/login_reg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all$', views.all, name='all'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

apps/travels_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add_plan, name='add_plan'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^destination/(?P<trip_id>\d+)$', views.destination, name='destination'),
    url(r'^destination/join/(?P<trip_id>\d+)$', views.join, name='join')
]

travel_buddy/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.login_reg_app.models import User as User
from apps.travels_app.models import Trip as Trip

class UserAdmin(admin.ModelAdmin):
  pass
admin.site.register(User, UserAdmin)

class TripAdmin(admin.ModelAdmin):
    pass
admin.site.register(Trip, TripAdmin)
# class FruitAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(Fruit, FruitAdmin)
#
# class DonutAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(Donut, DonutAdmin)
#
# class GroupAdmin(admin.ModelAdmin):
#   pass
# admin.site.register(Group, GroupAdmin)




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.default_app.urls', namespace='default')),
    url(r'^main/', include('apps.login_reg_app.urls', namespace='users')),
    url(r'^travels/', include('apps.travels_app.urls', namespace='travels')),
]

apps/travels_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_reg_app.models import User
from datetime import datetime
from django.utils.encoding import python_2_unicode_compatible


class TripManager(models.Manager):
    def add_trip(self, form_data, user):
        errors = []
        print(form_data['start_date'])
        if len(form_data['destination']) == 0 or len(form_data['plan']) == 0 or len(form_data['start_date']) == 0 or len(form_data['end_date']) == 0:
            errors.append("Please fill out all fields of the form!")
        if len(form_data['start_date']) > 0 or len(form_data['end_date']) > 0:
            start_date = datetime.strptime(form_data['start_date'], "%Y-%m-%d")
            end_date = datetime.strptime(form_data['end_date'], "%Y-%m-%d")
            print(start_date)
            if datetime.today() >= start_date:
                errors.append("Start date must be in the future")
            if start_date > end_date:
                errors.append("Trip end date cannot be before start date")
        if errors:
            return (False, errors)
        else:
            print("passed validations")
            # add trip to the database
            trip = Trip.objects.create(destination=form_data['destination'], plan=form_data['plan'], trip_maker=user, start_date=start_date, end_date=end_date)
            trip.travelers.add(user)
            return (True, "Trip successfully added")
    def join_trip(self, trip_id, user):
        print("adding trip to user's trips")
        trip = Trip.objects.get(id=trip_id)
        trip.travelers.add(user)
        return("Successfully added trip to your schedule!")


class Trip(models.Model):
    destination = models.CharField(max_length=255)
    plan = models.TextField()
    trip_maker = models.ForeignKey(User, related_name='trip')
    travelers = models.ManyToManyField(User, related_name='trips')
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = TripManager()
    def __str__(self):              # __unicode__ on Python 2
        return self.destination

apps/travels_app/views.py
from django.shortcuts import render, redirect
from ..login_reg_app.models import User
from .models import Trip
from django.contrib import messages
from django.core.urlresolvers import reverse
from datetime import datetime

# Create your views here.
def index(request):
    if 'user_id' in request.session:
        user = User.objects.get(id=request.session['user_id'])
        context = {
            'user': user,
            'trips': Trip.objects.all().exclude(travelers=user)
        }
        return render(request, 'travels_app/index.html', context)
    else:
        return redirect(reverse('users:index'))

def add_plan(request):
    return render(request, 'travels_app/add_plan.html')

def submit(request):
    if request.method == 'POST':
        print('validating plan')
        user = User.objects.get(id=request.session['user_id'])
        validation = Trip.objects.add_trip(request.POST, user)
        if validation[0]:
            messages.success(request, validation[1])
            return redirect(reverse('travels:index'))
        else:
            for error in validation[1]:
                messages.error(request, error)
    return redirect(reverse('travels:add_plan'))


def destination(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    users = trip.travelers.all().exclude(id=request.session['user_id']).exclude(id=trip.trip_maker.id)
    for user in users:
        print(user.name)
    print(trip)
    context = {
        'trip': Trip.objects.get(id=trip_id),
        'users': users
    }
    return render(request, 'travels_app/destination.html', context)

def join(request, trip_id):
    print("trying to join")
    user = User.objects.get(id=request.session['user_id'])
    validation = Trip.objects.join_trip(trip_id, user)
    messages.success(request, validation)
    return redirect(reverse('travels:index'))

apps/travels_app/templates/travels_app/add_plan.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Plan</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travels_app/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <header>
      <h1>Add a Trip</h1>
      <a href="{% url 'travels:index' %}">Home</a>
      <a href="{% url 'users:logout' %}">Logout</a>
    </header>
    {% if messages %}
        <ul class='messages'>
        {% for message in messages %}
            <li {% if message.tags %}class='{{message.tags}}'{% endif %}>{{message}}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <form class="" action="{% url 'travels:submit' %}" method="post">
      {% csrf_token %}
      Destination: <input type="text" name="destination" value="">
      <br>
      Description: <textarea name="plan" rows="8" cols="40"></textarea>
      <br>
      Travel Date From: <input type="date" name="start_date" value="">
      <br>
      Travel Date To: <input type="date" name="end_date" value="">
      <br>
      <input type="submit" name="submit" value="Add">
    </form>
  </body>
</html>

apps/travels_app/templates/travels_app/destination.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Destination</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travels_app/css/styles2.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <header>
      <a href="{% url 'travels:index' %}">Home</a>
      <a href="{% url 'users:logout' %}">Logout</a>
      {% if messages %}
          <ul class='messages'>
          {% for message in messages %}
              <li {% if message.tags %}class='{{message.tags}}'{% endif %}>{{message}}</li>
          {% endfor %}
          </ul>
      {% endif %}
      {% if trip %}
        <h1>{{trip.destination}}</h1>
        <ul class='trip'>
          <li>Planned By: {{trip.trip_maker}}</li>
          <li>Description: {{trip.plan}}</li>
          <li>Travel Date From: {{trip.start_date.date}}</li>
          <li>Travel Date To: {{trip.end_date.date}}</li>
        </ul>

        <br>
        <h2>Others users joining the trip:</h2>
        <ul>
        {% if users %}
          {% for person in users %}
            <li>{{person.name}}</li>
          {% endfor %}
        {% endif %}
        </ul>
      {% endif %}
    </header>
  </body>
</html>

apps/travels_app/templates/travels_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Travel Buddy</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'travels_app/css/styles.css' %}"media="screen" title="no title"  charset="utf-8">
  </head>
  <body>
    <header>
      <h1>Welcome {{user.name}}!</h1>
      <a id='logout' href="{% url 'users:logout' %}">Logout</a>
      {% if messages %}
          <ul class='messages'>
          {% for message in messages %}
              <li {% if message.tags %}class='{{message.tags}}'{% endif %}>{{message}}</li>
          {% endfor %}
          </ul>
      {% endif %}
    </header>
    <div id="yourTrips">
      <h2>Your Trip Schedules</h2>
      <table>
          <tr class='thead'>
              <th>Destination</th>
              <th>Travel Start Date</th>
              <th>Travel End Date</th>
              <th>Plan</th>
          </tr>
          {% if user.trips.all %}
          {% for trip in user.trips.all %}
          <tr class="{% cycle 'row2' 'row1' %}">
              <th><a href="{% url 'travels:destination' trip_id=trip.id %}">{{trip.destination}}</a></th>
              <th>{{trip.start_date.date}}</th>
              <th>{{trip.end_date.date}}</th>
              <th>{{trip.plan}}</th>
          </tr>
          {% endfor %}
          {% endif %}
        </table>
    </div>
    <div id="others">
      <h2>Other User's Travel Plans</h2>
      <table>
          <tr class='thead'>
              <th>Name</th>
              <th>Destination</th>
              <th>Travel Start Date</th>
              <th>Travel End Date</th>
              <th>Do You Want to Join?</th>
          </tr>
          {% if trips %}
          {% for trip in trips %}
          <tr class="{% cycle 'row2' 'row1' %}">
              <th>{{trip.trip_maker}}</th>
              <th><a href="{% url 'travels:destination' trip_id=trip.id %}">{{trip.destination}}</a></th>
              <th>{{trip.start_date.date}}</th>
              <th>{{trip.end_date.date}}</th>
              <th><a href="{% url 'travels:join' trip_id=trip.id %}">Join</a></th>
          </tr>
          {% endfor %}
          {% endif %}
      </table>
    </div>
    <a id="add" href="{% url 'travels:add_plan' %}">Add Travel Plan</a>
  </body>
</html>